a = input('Digite algo: ')
print('O tipo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número?', a.isnumeric())
print('É um alabético?', a.isalpha())
print('É um alfanumérico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())